opt_in_rules:
    - anyobject_protocol
    - array_init
    - collection_alignment
    - explicit_init
    - file_name_no_space
    - force_unwrapping
    - multiline_arguments
    - multiline_parameters
    - sorted_imports
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

reporter: "xcode"
